workflows:
  android-build:
    name: Android Build
    max_build_duration: 60

    environment:
      node: 20
      groups:
        - mobile-env

    scripts:
      - name: Install dependencies
        script: |
          cd mobile-app
          npm install

      - name: Build Android APK
        script: |
          cd mobile-app/android
          chmod +x gradlew
          ./gradlew assembleRelease

    artifacts:
      - mobile-app/android/app/build/outputs/**/*.apk
