workflows:
  android-build:
    name: Android Build
    max_build_duration: 60

    environment:
      node: 20
      groups:
        - mobile-env

    scripts:
      - name: Install dependencies
        script: |
          cd mobile-app
          npm install

      - name: Sync Expo native config
        script: |
          cd mobile-app
          npx expo prebuild

      - name: Build Android APK
        script: |
          cd mobile-app/android
          chmod +x gradlew
          ./gradlew assembleRelease --warning-mode all

    artifacts:
      - mobile-app/android/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - shendgesuraj07@gmail.com
